bind = "0.0.0.0:25570"
ip_forward = true
online_mode = true
max_players = 20
motd = "&3Enter the rift."

[[servers]]
id = "lobby"
address = "localhost:25565"
# you can have multiple default servers
# connecting players will be randomly assigned to a default server
default = true
